name: Publish Docker image for multiple CUDA architectures - Runs daily 1AM EST

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build-textgen:
    strategy:
      matrix:
        arch:
          [
            "7.5",
            "8.0",
            "8.6",
            "8.9",
            "9.0"
          ]
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: TORCH_CUDA_ARCH_LIST=${{ matrix.arch }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/textgen-nvidia-${{ matrix.arch }}:latest
          platforms: linux/amd64,linux/arm64/v8
